name: money
description: >
  Dart implementation of Fowler's Money pattern using built_value
  Built on top of https://github.com/LitGroup/money.dart

version: 0.0.1
author: Vinicius Andrade <vbandrade@gmail.com>
homepage: https://github.com/vbandrade/money.dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  built_collection: ">=2.0.0 <5.0.0"
  built_value: ">=5.5.5 <7.0.0"

dev_dependencies:
  test: ">=1.5.0 <2.0.0"
  build_test: ^0.10.0
  build_runner: ^1.0.0
  built_value_generator: ^6.1.6
